### PR TITLE
Integrate min-const-generics.

### LINKED ISSUE #373: Can't statically construct Vector
This was possible in much older nalgebras. However now they have a private `PhantomData` field.

### LINKED ISSUE #526: Const generics (RFC 2000) refactor
[Const generics](https://github.com/rust-lang/rfcs/blob/master/text/2000-const-generics.md) rust-lang/rust#44580 need to be added into nalgebra, since it is one of the greatest beneficiaries from this feature. I propose that we maintain a `nalgebra-cg` crate on crates.io that depends on nightly until the feature is merged. The reason this might be preferable over using a feature flag is that almost everything in this library is going to need to be refactored to use const generics.

Although const generics are not yet in nightly, I propose using rust-lang/rust#53645 (varkor's branch) to start development now so that it can be available on merge and to assist in finding bugs via integration.

### LINKED ISSUE #590: from_fn cannot be used with dimensions from typenum::U*
The following code for generating large random complex matrices doesn't seem to work.

```extern crate num;
extern crate rand;
extern crate typenum;
extern crate nalgebra;

use num::complex::Complex64;
use rand::prelude::*;

fn main() {
    let mut r = rand::thread_rng();
    let c = nalgebra::MatrixMN::<Complex64,typenum::U6,typenum::U1024>::from_fn(
        |_,_| Complex64 { re: r.gen(), im: r.gen() }
        );
    println!("Matrix {}", c);
}
```

The compiler output is:

> error[E0599]: no function or associated item named `from_fn` found for type `nalgebra::Matrix<num::Complex<f64>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B1>, typenum::B0>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, nalgebra::ArrayStorage<num::Complex<f64>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B1>, typenum::B0>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>>>` in the current scope
>   --> src/main.rs:11:73
>    |
> 11 |     let c = nalgebra::MatrixMN::<Complex64,typenum::U6,typenum::U1024>::from_fn(
>    |             ------------------------------------------------------------^^^^^^^
>    |             |
>    |             function or associated item not found in `nalgebra::Matrix<num::Complex<f64>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B1>, typenum::B0>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, nalgebra::ArrayStorage<num::Complex<f64>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B1>, typenum::B0>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>>>`
>    |
>    = note: the method `from_fn` exists but the following trait bounds were not satisfied:
>            `nalgebra::DefaultAllocator : nalgebra::allocator::Allocator<num::Complex<f64>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B1>, typenum::B0>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>>`
>            `typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B1>, typenum::B0> : nalgebra::DimName`
> 
> error[E0277]: the trait bound `typenum::UTerm: nalgebra::DimName` is not satisfied
>   --> src/main.rs:11:13
>    |
> 11 |     let c = nalgebra::MatrixMN::<Complex64,typenum::U6,typenum::U1024>::from_fn(
>    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `nalgebra::DimName` is not implemented for `typenum::UTerm`
>    |
>    = note: required because of the requirements on the impl of `nalgebra::DimName` for `typenum::UInt<typenum::UTerm, typenum::B1>`
>    = note: required because of the requirements on the impl of `nalgebra::DimName` for `typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B1>`
>    = note: required because of the requirements on the impl of `nalgebra::DimName` for `typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B1>, typenum::B0>`
>    = note: required because of the requirements on the impl of `nalgebra::allocator::Allocator<num::Complex<f64>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B1>, typenum::B0>, typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>, typenum::B0>>` for `nalgebra::DefaultAllocator`
> 
> error: aborting due to 2 previous errors
> 
> Some errors occurred: E0277, E0599.
> For more information about an error, try `rustc --explain E0277`.
> error: Could not compile `complex`.
> 
> To learn more, run the command again with --verbose.

### LINKED ISSUE #621: You can't use typenum consts for sub-128 numbers
As titles says, explicitly stating in docs that typenum consts don't work for <128 numbers would help newcomers avoid confusing errors. I have already posted [similar issue](https://github.com/rustsim/nalgebra.org/issues/25) on nalgebra.org's repo.

### LINKED ISSUE #852: min_const_generics sintaxe in nalgebra, removing typenum dependency
With new [min_const_generics stabilize](https://github.com/rust-lang/rust/pull/79135) in [rust 1.51](https://github.com/rust-lang/rust/releases/tag/1.51.0) is possible think about use `Matrix<3, 2>` sintaxe instead of current `Matrix<U3, U2>`?

### LINKED ISSUE #858: Weird compilation error (error: could not compile `generic-array`)
So I wanted to use `nalgebra` for one of my projects and I got this error 

```
❯ wasm-pack build --dev

[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling generic-array v0.14.4
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/build/generic-array-ace44042ed9a1092/build_script_build-ace44042ed9a1092.build_script_build.a2apzwkb-cgu.0.rcgu.o" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/build/generic-array-ace44042ed9a1092/build_script_build-ace44042ed9a1092.build_script_build.a2apzwkb-cgu.1.rcgu.o" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/build/generic-array-ace44042ed9a1092/build_script_build-ace44042ed9a1092.build_script_build.a2apzwkb-cgu.2.rcgu.o" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/build/generic-array-ace44042ed9a1092/build_script_build-ace44042ed9a1092.build_script_build.a2apzwkb-cgu.3.rcgu.o" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/build/generic-array-ace44042ed9a1092/build_script_build-ace44042ed9a1092.build_script_build.a2apzwkb-cgu.4.rcgu.o" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/build/generic-array-ace44042ed9a1092/build_script_build-ace44042ed9a1092.build_script_build.a2apzwkb-cgu.5.rcgu.o" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/build/generic-array-ace44042ed9a1092/build_script_build-ace44042ed9a1092.build_script_build.a2apzwkb-cgu.6.rcgu.o" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/build/generic-array-ace44042ed9a1092/build_script_build-ace44042ed9a1092.build_script_build.a2apzwkb-cgu.7.rcgu.o" "-o" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/build/generic-array-ace44042ed9a1092/build_script_build-ace44042ed9a1092" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/build/generic-array-ace44042ed9a1092/build_script_build-ace44042ed9a1092.xeu0o7k5dcbrlyc.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/deps" "-L" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/deps/libversion_check-cfc36a71ddbbb5ae.rlib" "-Wl,--start-group" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-93cbfed54dd1bac8.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-db33fe383d9e671a.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-4afe0e223ea50f9d.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-76d88ad8c833f039.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-762cea37cccf8abe.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-8de1e75656157df8.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-76f54e5a49eca8e8.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-d7aed80bcad8813a.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-a3916e8afa60a160.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-eaacce9b176ef080.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-81e497cd060f0dda.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-949464f6d582f46f.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-1ffc094785c92121.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-f19c324859e53f08.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-0b82195f1020bf42.rlib" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-4f2339b0071e1016.rlib" "-Wl,--end-group" "/home/puipuituipui/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-774a5f30b27a1f9c.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  = note: /usr/bin/ld: /home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/deps/libversion_check-cfc36a71ddbbb5ae.rlib(version_check-cfc36a71ddbbb5ae.version_check.23wlh7fw-cgu.10.rcgu.o): in function `version_check::is_min_version':
          /home/puipuituipui/.cargo/registry/src/github.com-1ecc6299db9ec823/version_check-0.9.3/src/lib.rs:210: undefined reference to `version_check::version::Version::read'
          /usr/bin/ld: /home/puipuituipui/.cargo/registry/src/github.com-1ecc6299db9ec823/version_check-0.9.3/src/lib.rs:210: undefined reference to `version_check::version::Version::parse'
          /usr/bin/ld: /home/puipuituipui/.cargo/registry/src/github.com-1ecc6299db9ec823/version_check-0.9.3/src/lib.rs:211: undefined reference to `<version_check::version::Version as core::cmp::PartialOrd>::ge'
          /usr/bin/ld: /home/puipuituipui/Github/wasml-linreg/wasml-linreg/target/debug/build/generic-array-ace44042ed9a1092/build_script_build-ace44042ed9a1092: hidden symbol `_ZN73_$LT$version_check..version..Version$u20$as$u20$core..cmp..PartialOrd$GT$2ge17h1f1bedaf2e9aeabeE' isn't defined
          /usr/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `generic-array`

To learn more, run the command again with --verbose.
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
  full command: "cargo" "build" "--lib" "--target" "wasm32-unknown-unknown"
```

I tried googling but I can't seem to even understand what the problem is since I haven't even used the library yet, just added it to `Cargo.toml`

### PR DESCRIPTION
**Pull request by sebcrozet**
Fix #852, fix #858, fix #621, fix #590, fix #526, fix #373

This PR isn't intended to be merged right now. It won't be merged before `min-const-generics` is stabilized. Though I wanted to submit this to show that `min-const-generics` is powerful enough to let us replace `generic-array` by a regular array based on const-generics.

This PR does not do everything we can change when min-const-generics will stabilize, but it contains all the changes needed to make everything work. More changes can be made to make the API a bit nicer though (e.g. to allow the user to write `Point<f32, 10>` instead of `Point<f32, Const<10>>` for example).

The idea here is to replace the typenum numbers (and our own number types `U1, U2, etc.`) by a new struct wrapping an integer: `struct Const<const T: usize>`, and define an array storage like this:

```rust
struct ArrayStorage<N, const R: usize, const C: usize> {
    data: [[N; R]; C]
}
```
Then we have to adapt all the relevant trait implementations and _voilà!_

### Limitation
There is one limitation here. Because `min-const-generics` does not allow operations on the const parameter, some method modifying the dimension of a matrix won't work. For example `Vector<N, Const<2>>::push` should return a `Vector<N, Const<3>>`, yet we can't write something like this:

```rust
impl<const R: usize> Vector<N, Const<R>> {
    fn push(&self) -> Vector<N, Const<{R + 1}>>;
}
```

because the `{R + 1}` isn't allowed yet. So we still need to use `typenum` as a workaround here. Basically, we have two traits `ToTypenum` and `ToConst` which we use to map `Const<1>` to `typenum::U1`, `Const<2>` to `typenum::U2`, etc. That way, we can type our `push` function like this:

```rust
impl<const R: usize> Vector<N, Const<R>> {
    fn push(&self) -> Vector<N, <Sum<<Const<R> as ToTypenum>::Output, typenum::U1> as ToConst>::Output
    where Const<R>: ToTypenum,
               <Const<R> as ToTypenum>::Output: Add<typenum::U1>,
               Sum<<Const<R> as ToTypenum>::Output, typenum::U1>: ToConst;
}
```

The code I use in `nalgebra` for this is actually much nicer because all the gory details  can be hidden behind our `DimSum`, `DimSub`, etc. traits (which already existed before this PR).

So the limitation here is that methods like `push` that do some operations on the dimension of the input matrix will only work with matrices having dimensions with a type implementing `ToTypenum`. However we can only implement our `ToTypenum` and `ToConst` traits for a finite number of types. In this PR I implemented `ToTypenum` for `Const<1>` to `Const<128>`. We may add more if someone needs it. So right now methods like `push` will only work on statically-sized matrices with dimensions smaller than 128 (but it will continue to work on all dynamically-sized matrices). Methods that don't rely on this kind of type-level dimension addition or subtraction, will work with all dimensions (including these that don't implement `ToTypenum`).

### CODE REVIEW

**Comment by sebcrozet** [comment]
I believe I have done everything I can think of regarding the integration of const-generics to nalgebra. 
Here are some benefits of const-generics:
- The `DefaultAllocator: Allocator` traits are no longer needed whenether only dimensions given as const integers are specified. For example the code related to the `Point<T, const D: usize>` no longer requires any allocator bounds.
- Debugging vectors/matrices with small sizes becomes much nicer because the debugger gives a much nicer view of arrays as compared to `GenericArray`.
- The `new` constructors of matrices, vectors, points, and translations, with a number of rows and columns smaller or equal to 6, are now `const fn`.
- The `Quaternion::new` constructor is also a `const fn`.

Because Rust doesn't allow to write a type parameter to be either a const or a type, I had to make some changes to our aliases. In particular, we have:

- `OMatrix<T, R: Dim, C: Dim>`: for owned matrices (formerly called `MatrixMN`).
- `SMatrix<T, const R: usize, const C: usize>`: for statically-allocated matrices.
- `DMatrix<T>`: for dynamically-allocated matrices.

The same applies to vectors: `OVector, SVector, DVector`.
The `MatrixN` alias has been deprecated for simplicity (just use `OMatrix<T, D, D>` instead.

I renamed the scalar type parameter from `N` to `T` because `N` wasn't idiomatic.

File: src/base/indexing.rs [hunk 1]
```diff
@@ -2,12 +2,12 @@
...
 use crate::base::storage::{Storage, StorageMut};
 use crate::base::{
-    Dim, DimDiff, DimName, DimSub, Dynamic, Matrix, MatrixSlice, MatrixSliceMut, Scalar, U1,
+    Const, Dim, DimDiff, DimName, DimSub, Dynamic, Matrix, MatrixSlice, MatrixSliceMut, Scalar, U1,
 };
 
 use std::ops;
 
-// N.B.: Not a public trait!
+// T.B.: Not a public trait!
```
Comment (jswrenn) [inline src/base/indexing.rs:10]: Oops, I don't think *this* `N` was supposed to be renamed to `T`!
